### ISSUE TITLE
Default value not executed

### ISSUE THREAD

**Issue by BigTows** [ivido/helm-deploy#1]
https://github.com/ivido/helm-deploy/blob/a24d7d10543a7a7919514a36d667667c0a3fc4e3/index.js#L87

this is unreached statement

Because tagsFiled always is list `[]`

**Comment by BigTows** [comment]
And also this is crashing my pipeline xD

**Comment by jarimayenburg** [comment]
Apologies, hadn't realized this action was used by anyone outside of our company. Will take that into account next time. Thanks for the PR!
